# Generated by Django 5.1.4 on 2025-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_desc_destination_offer_destination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
